### ISSUE TITLE
Use of custom template engines

### ISSUE THREAD

**Issue by Sharptsa** [volatiletech/authboss#101]
I would like to use pongo2 as my default template engine instead of golang template.

Is there a way to make it happen when loading Authboss' views ? Overriding the function that loads templates ?

**Comment by aarondl** [comment]
Currently there's no way to do that. Happy to accept a PR and will ensure there's some consideration for it in v2

**Comment by Sharptsa** [comment]
I am just starting to learn Golang so do not expect me to do that kind of PR before a while, but definitly a nice feature to have in the future. 👍

**Comment by aarondl** [comment]
This will be possible in v2.
