### ISSUE TITLE
Add the possibility to generate a login box ( or register box ) that can be rendered outside authboss's entrypoints 

### ISSUE THREAD

**Issue by rahal** [volatiletech/authboss#102]
Hi, 
For now, we can login or register only from authboss's routes ( login and register )
Is there a simple way to have a login or register box  to use inside my templates.

Thank you

**Comment by aarondl** [comment]
Hey Rahal. Somehow I thought I had replied to this already. You can simply create a form that looks exactly like the authboss form and make sure it posts to the correct location and it should work :) There's no truly simply way, but you can copy it's template as a starting point.

https://github.com/go-authboss/authboss/blob/master/internal/response/templates/login.html.tpl

**Comment by aarondl** [comment]
Also will consider for v2.

**Comment by aarondl** [comment]
v2 should support all of this now. Please see the releases page for more information.
