### ISSUE TITLE
Partial template issue

### ISSUE THREAD

**Issue by kaiomagalhaes** [volatiletech/authboss#119]
Hey guys, I would like to know if there is any way to include templates on my main layout. On your example you guys seem to be only rendering one:

```
	{{template "yield" .}}
```

Which is the module template like register form

But I would like to do something like: 
```
	{{template "navbar" .}}
	{{template "yield" .}}
	{{template "footer" .}}
```

And I didn't see any place where I can pass these navbar/footer templates to be compiled and rendered alongside with the module template. Is there any way to do it? Thanks!

**Comment by aarondl** [comment]
I actually had a response typed out for this before the weekend. Not sure why I didn't send it lol.

This should be totally possible now. As in the configuration struct there is a Layout template that you can supply that has as many sub-templates loaded in as you want. The important thing is just that there's an authboss section somewhere. There is some docs for this: https://github.com/go-authboss/authboss#-views

**Comment by aarondl** [comment]
Stale, closing.
