### ISSUE TITLE
Whether is authboss suitable for microservice/serverless  ?

### ISSUE THREAD

**Issue by goodforever** [volatiletech/authboss#146]
Whether is authboss suitable for microservice/serverless  ?
I want use authboss as a public auth service for all business

**Comment by aarondl** [comment]
For serverless, no I don't think so. Though it really depends what kind of Auth you're doing.

It's made for a monolith web application but it really depends again, how are you handling authentication across all your microservices? It's probably lacking if you try to coordinate auth across many microservices.

**Comment by goodforever** [comment]
We want to use only one auth service for many web site. it can be server, microservice or serverless. 
Do you think I can build it based on authboss ?

**Comment by aarondl** [comment]
It could possibly be made to work yeah, but it would require a fair amount of modification to allow pass through to other sites as well as coming up with a mechanism to share auth cookies and accept them in multiple places. Many microservice people are using JWT with a central auth server. You could modify this project to do that I think.

**Comment by goodforever** [comment]
@aarondl thanks
