### ISSUE TITLE
Upgrade path from v1 to v2?

### ISSUE THREAD

**Issue by jack-chung** [volatiletech/authboss#147]
Hi,

I'm wondering how different is v2 going to be and if there is an upgrade path that is being designed?
I'm currently using a very heavily customized v1 to power our JSON auth API (did it without modifying any authboss code) and wondering what my future options are...

Regards,
Jack

**Comment by aarondl** [comment]
Hey Jack. It's going to be pretty different.

The main changes are in the core interfaces which now deal with `context`.
https://github.com/volatiletech/authboss/blob/dev/context.go
https://github.com/volatiletech/authboss/blob/dev/storer.go
https://github.com/volatiletech/authboss/blob/dev/mailer.go
https://github.com/volatiletech/authboss/blob/dev/client_state.go
https://github.com/volatiletech/authboss/blob/dev/renderer.go

These interfaces have also now been "simplified", especially the Storer. These are almost finalized. So the biggest headache when upgrading will really be having to re-implement storers, mailers etc. Everything else should just work seamlessly.

**Comment by rojakcoder** [comment]
Hi Aaron,

Will v2 be in a separate project or will it replace v1 in the current master branch?

**Comment by aarondl** [comment]
It will replace the master branch. The tags for v1 are always available and will continue to work.

**Comment by punkle64** [comment]
Hi Aaron,

When do you expect v2 to be available?

**Comment by aarondl** [comment]
@punkle64 I can't really say. Unfortunately I'm not really actively taking care of anything except bugs on any of my open source projects due to real life stuff right now. :(

**Comment by aarondl** [comment]
Should be out in weeks.
