### ISSUE TITLE
requires a very small max password length even though it uses bcrypt

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#149]
The maximum password length is set very low, at 8, by default, even though the password is hashed with bcrypt. This could be made, at the least, much, much higher but can, for most purposes, be unbounded.

**Comment by jmhodges** [comment]
Oh, well, I mean, unbounded but up to some large number that servers and clients can reasonably send (esp. in the password change form context).

**Comment by aarondl** [comment]
Thanks for the PR. Though it is kind of a breaking change if people have this is production. Let's wait for v2. Though the default that's here is pretty shameful, not sure why we put that in to be honest, you're absolutely correct in all ways.

**Comment by aarondl** [comment]
Closing as this was discussed in the PR.
