### ISSUE TITLE
document places that use FlashSuccessKey and FlashErrorKey

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#151]
I just figured out that I needed to add some Gets of authboss.FlashSuccessKey and FlashErrorKey to my / templates that `Defaults` sets the RecoverOKPath to. It would be nice if the places where FlashSuccessKey and FlashErrorKey are use were documented so that folks could know when they'll need to display them.

**Comment by aarondl** [comment]
There is some documentation here about the views.
https://github.com/volatiletech/authboss#-views
And it does reference the flash keys though it doesn't really say you should use them with the exception of the examples. So we should probably improve that, you're right.

**Comment by aarondl** [comment]
Currently in v2, it'd be everywhere you render data COULD have a flash message. And so you should be prepared to always be rendering it if you're receiving data and writing it out. See the authboss-sample for how this is handled (in a layout level template so we only have to code this once).
