### ISSUE TITLE
Deprecating gopkg.in

### ISSUE THREAD

**Issue by jack-chung** [volatiletech/authboss#156]
Hello Aaron,

Is the code currently in master branch considered v1 or v2?
If I want the latest v1, should I still be using gopkg.in/v1 or the v1 tags on volatiletech/authboss? 

Attempting to import v1.1.0 from volatiletech failed to compile, because the code in v1.1.0 itself imports from gopg.in/v1, specifically the internal packages causing the errors. 

It failed with this:
vendor/github.com/volatiletech/authboss/auth/auth.go:11:2: use of internal package not allowed

**Comment by aarondl** [comment]
v2 is meant to be used as semver.
v1 is still meant to be used with gopkg.in
