### ISSUE TITLE
authboss mailer requires HTMLBody to be set

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#160]
It's undocumented that authboss.Mailer requires HTMLBody to be set. I just sent a bunch of blank-looking emails to users because I assumed if HTMLBody was not set, it would not be included in the message body.

**Comment by aarondl** [comment]
I'm really sorry about that :( Will try to fix this issue in v2.

**Comment by aarondl** [comment]
Fixed here: https://github.com/volatiletech/authboss/commit/e9c5d3e13c22e0ca296770e9448ab4bdbff1a37b

As the commit describes, the problem is that the section for the HTML was not completely removed and so gmail would show it assuming that it was showing something useful (which was not the case).
