### ISSUE TITLE
Is it a good idea to start a project with v1, given the upgrade?

### ISSUE THREAD

**Issue by sjain07** [volatiletech/authboss#162]
Since there is going to be a major upgrade in the library with only 6 months of support. Does it make sense to start a new project which utilizes this library? If not any alternatives. If yes how much effort is it realistically going to take to upgrade to v2

**Comment by aarondl** [comment]
I don't think it does make sense. I can claim that it's probably not THAT much effort to upgrade, but I think it will be a lot of breakage and it'll end up being mostly restarting from scratch. Having said that I'm hoping to have v2 done in about a week's time? Hopefully that helps.
