### ISSUE TITLE
[question] compatible with Buffalo

### ISSUE THREAD

**Issue by danikarik** [volatiletech/authboss#163]
Hi!
I’ve played with https://github.com/gobuffalo/buffalo and wondering about compatibility with authboss. Authboss uses different renderer compare with plask (in buffalo). Also buffalo has own CSRF middleware which puts token automatically.

Sorry if my question seems weirdly, I’m newby in Golang web.

**Comment by aarondl** [comment]
I think it'd be a stretch to integrate it into v1, but v2 should fit nicely. I'm working on it and it should be ready soon-ish. Also the mailing list is a much better place for these discussions :)

**Comment by frederikhors** [comment]
Dear @markbates `authboss` can become Go's "`devise`" with Buffalo.

Would it be possible to invest a few minutes of your time?

Here an official sample with `chi` router: https://github.com/volatiletech/authboss-sample

**Comment by markbates** [comment]
I don’t have cycles to spare; but I’m sure the community would love it. 

It’s also not something I would use, so I would be the wrong person to ask.

**Comment by frederikhors** [comment]
@markbates Can I ask you what do you use for this kind of features?

**Comment by markbates** [comment]
I roll my own.
