### ISSUE TITLE
AuthBoss as an OAuth2 provider

### ISSUE THREAD

**Issue by jcantonio** [volatiletech/authboss#166]
Hello,
Is authboss also an OAuth provider: i.e. can register server with client Id and secret.
Or its OAuth features are limited to use other providers like Google, Facebook etc...
Thanks!
Jean-Claude

**Comment by aarondl** [comment]
Authboss is simply an OAuth2 client. It has no server capabilities in that regard. :)

**Comment by jcantonio** [comment]
@aarondl : Thank you for your response..
