### ISSUE TITLE
Passing custom function map to AB templates in v2?

### ISSUE THREAD

**Issue by punkle64** [volatiletech/authboss#168]
It seems that currently AB templates use their own function map -> authboss/internal/response/response.go:
funcMap := template.FuncMap{
		"title": strings.Title,
		"mountpathed": func(location string) string {
			if ab.MountPath == "/" {
				return location
			}
			return path.Join(ab.MountPath, location)
		},
	}
Would it be possible in the future (in v2 obviously) to pass an additional (custom) funtion map? This would allow much more advanced manipulation of AB views.

Thanks in advance,
Daniele

**Comment by aarondl** [comment]
Hey there @punkle64. Currently in v2 Authboss makes no presuppositions about how you'd like to render your content. Most of the existing v1 functionality has been moved into the [authboss-renderer](https://github.com/volatiletech/authboss-renderer) package. I'd accept a pull request there making it simple to merge the template functions there if you'd like. Or you're welcome to implement your own renderer that does exactly what you want :)

See this documentation:
https://github.com/volatiletech/authboss/blob/v2/README.md#rendering-views

v2 is currently in rc phase, I'd encourage you to try it out.
