### ISSUE TITLE
Not able to pass arbitrary field values in User Registration

### ISSUE THREAD

**Issue by punkle64** [volatiletech/authboss#173]
In my user registration template I have several arbitrary fields. And somehow they are not included in the arbitrary list with the exception of "password", "name" and "email". I tried several things:

```
ab.Config.Modules.RegisterPreserveFields = []string{"name", "surname", "gender", 
  "description", "clientweightmax_int", "clientheightmax_int", "phonenumber","email", "username"}

ab.Config.Core.BodyReader = defaults.NewHTTPBodyReader(false, true)
ab.Config.Core.BodyReader.(*defaults.HTTPBodyReader).Whitelist["register"] = []string{"name", 
  "surname", "gender", "description", "clientweightmax_int", "clientheightmax_int",
  "phonenumber","email", "username"}
```

But the only non-authboss field I get is "name" (very weird I know...), which gets correctly stored in the arbitrary list.

My template looks like:

```
<input type="text" class="form-control" name="name" placeholder="{{l "Name" $.lang}}" value="{{.name}}" autofocus required/> (<-- this works)
<input type="text" class="form-control" name="surname" placeholder="{{l "Surname" $.lang}}" value="{{.surname}}" required/> (<-- this does not)
```

I might be doing something really silly here but I don't seem to find the issue.

Thank you in advance for your help,
Daniele

**Comment by punkle64** [comment]
I did implement the Arbitrary user interface. And I'm aware that preserve fields are just to refill the form in case of error. But I had to try... :)

```
// PutArbitrary inserts registration field names into user
func (u *User) PutArbitrary(values map[string]string) {
  fmt.Println("PutArbitrary. values: ", values)
  var err error
	if n, ok := values["name"]; ok {
		u.Name, err = utils.ValidateName(n)
	}
	if n, ok := values["surname"]; ok {
		u.Surname, err = utils.ValidateName(n)
	}
	if n, ok := values["gender"]; ok {
		u.Gender, err = utils.ValidateGender(n)
	}
	if n, ok := values["description"]; ok {
		u.Description, err = utils.ValidateDescription(n)
	}
	if n, ok := values["clientweightmax_int"]; ok {
		u.Clientweightmax, err = utils.ValidateInt(n, cfg.Constants.MinWeight, cfg.Constants.MaxWeight)
	}
	if n, ok := values["clientheightmax_int"]; ok {
		u.Clientheightmax, err = utils.ValidateInt(n, cfg.Constants.MinHeight, cfg.Constants.MaxHeight)
	}
	if n, ok := values["phonenumber"]; ok {
		u.Phonenumber, err = utils.ValidatePhone(n)
	}
	if n, ok := values["email"]; ok {
		u.Email, err = utils.ValidateEmail(n)
	}
	if err != nil {
	  log.LogError("Some fields couldn't be validated and won't be insterted in the DB", err, false)
	}
	ab_updateUser(u.Username, *u)
}

// GetArbitrary from user
func (u User) GetArbitrary() map[string]string {
  return map[string]string{
    "name": u.Name,
    "surname": u.Surname,
    "gender": u.Gender,
    "description": u.Description,
    "clientweightmax": strconv.Itoa(u.Clientweightmax),
    "clientheightmax": strconv.Itoa(u.Clientheightmax),
    "phonenumber": u.Phonenumber,
    "email": u.Email,
  }
}
```

**Comment by aarondl** [comment]
Yep, I'm not concerned about the details of the implementations. As long as they're implemented that's good enough for me. (Though I am concerned you have a function name with an underscore in it!)

Like I said in a long winded way, you're not getting preserved fields correctly because in this snippet you showed me you are not referencing `.preserve` which is where all the preserved fields live.
```html
<input type="text" class="form-control" name="name" placeholder="{{l "Name" $.lang}}" value="{{.name}}" autofocus required/> (<-- this works)
<input type="text" class="form-control" name="surname" placeholder="{{l "Surname" $.lang}}" value="{{.surname}}" required/> (<-- this does not)
```

Which is why I showed you the authboss sample template which is correctly referencing the preserved fields:
https://github.com/volatiletech/authboss-sample/blob/v2/ab_views/html-templates/register.tpl#L7

Fix your templates to correctly look in the `.preserve` field of the data for preserved fields and it should start working. Though I can't explain why `name` is working now, that's crazy to me.

**Comment by punkle64** [comment]
Hi Aaron,

I think I explained myself in a very confusing way - sorry:), or I'm not
understanding what you meant. I'm not saying that the preserve feature
doesn't work (didn't test it yet), what I'm saying is that I don't manage
to save the arbitrary fields back in the DB with the sole exception of the
"name". "username" doesn't make it to the DB either even though I am using
it as primary ID for authboss. I nevertheless tried to put in the suggested
preserve template variable like in the authboss example for the "surname",
but it doesn't work for that either:

<input type="text" class="form-control" name="surname" placeholder="{{l
"Surname" $.lang}}" value="{{with .preserve}}{{with
.surname}}{{.}}{{end}}{{end}}" required/>

If you think there is no issue with authboss, then I guess I will just
debug my code deeper to find the bug (it might very well be something silly
on my side, that somehow I can't see), and you may close this issue.

Thanks again for your help,
Daniele

2018-07-06 17:59 GMT+02:00 Aaron L <notifications@github.com>:

**Comment by punkle64** [comment]
BTW, thanks for the heads up on the function with underscore, I'm quite new to golang and wasn't aware of the convention:)

**Comment by punkle64** [comment]
In the end it was my own bug, I was overwriting my configuration:

```
ab.Config.Core.BodyReader.(*defaults.HTTPBodyReader).Whitelist["register"] = []string{"name", 
  "surname", "gender", "description", "clientweightmax_int", "clientheightmax_int",
  "phonenumber","email", "username"}
```

with the Authboss v2 example one:

```
Whitelist: map[string][]string{"register": []string{"email", "name", "password"},},
```

Sorry for the noise, please close this ticket.
