### ISSUE TITLE
V2 Doesn't implement configurable PrimaryID?

### ISSUE THREAD

**Issue by IvRRimum** [volatiletech/authboss#174]
I see that V1 Mentions it, but the V2 not even in the doc.

**Comment by aarondl** [comment]
It's a hard-coded thing in v1. In v2 it doesn't care, the interface for user demands you return a PID as a string. This can be whatever you want. An email address, a stringified user ID, a uuid. It doesn't mention it because PID is involved in all the interfaces so it was meant to be a bit self explanatory with the godocs available.

Reopen if you think this is insufficient, but please let me know where the confusion lies. Currently I'm assuming since you were familiar with v1 you're leading yourself astray a bit.

**Comment by IvRRimum** [comment]
I meant the form. Currently you have to use <input name="email" .. />, is there a way i can change "email" to, lets say "emailOrUsername"?

Thanks for swift responses.

**Comment by aarondl** [comment]
You can control literally everything using the interfaces that exist. If you look at the BodyReader interface it understands how to read a body from an http request. The default body reader is expecting certain names for the parameters:
https://github.com/volatiletech/authboss/blob/v2/defaults/values.go

You can replace this interface to do anything you want. Here its configurable to take username or email.

**Comment by IvRRimum** [comment]
@aarondl Yeah, i already checked it out:

```
type HTTPBodyReader struct {
	// ReadJSON if turned on reads json from the http request
	// instead of a encoded form.
	ReadJSON bool

	// UseUsername instead of e-mail address
	UseUsername bool

	// Rulesets for each page.
	Rulesets map[string][]Rules
	// Confirm fields for each page.
	Confirms map[string][]string
	// Whitelist values for each page through the html forms
	// this is for security so that we can properly protect the
	// arbitrary user API. In reality this really only needs to be set
	// for the register page since everything else is expecting
	// a hardcoded set of values.
	Whitelist map[string][]string
}
```

and if i dig deeper:
```
	var pid string
	var pidRules Rules

	if useUsernameNotEmail {
		pid = "username"
		pidRules = Rules{
			FieldName: pid, Required: true,
			MatchError: "Usernames must only start with letters, and contain letters and numbers",
			MustMatch:  regexp.MustCompile(`(?i)[a-z][a-z0-9]?`),
		}
	} else {
		pid = "email"
		pidRules = Rules{
			FieldName: pid, Required: true,
			MatchError: "Must be a valid e-mail address",
			MustMatch:  regexp.MustCompile(`.*@.*\.[a-z]{1,}`),
		}
	}
```

Would be great to clarify how exacly one can easally.

Heres how i currently am doing this and it's still not recognizing my custom pid and using `email` instead.

```
	emailRule := defaults.Rules{
		FieldName: "email", Required: true,
		MatchError: "Must be a valid e-mail address",
		MustMatch:  regexp.MustCompile(`.*@.*\.[a-z]{1,}`),
	}
	usernameRule := defaults.Rules{
		FieldName: "username",
		Required:  true,
		MinLength: 4,
	}
	emailOrUsernameRule := defaults.Rules{
		FieldName: "email_or_username",
		Required:  true,
		MinLength: 4,
	}
	passwordRule := defaults.Rules{
		FieldName: "password",
		Required:  true,
		MinLength: 4,
	}
	ab.Config.Core.BodyReader = defaults.HTTPBodyReader{
		ReadJSON: true,
		Rulesets: map[string][]defaults.Rules{
			"login":    {emailOrUsernameRule, passwordRule},
			"register": {emailRule, usernameRule, passwordRule},
		},
		Confirms: map[string][]string{
			"register": {"password", authboss.ConfirmPrefix + "password"},
		},
		Whitelist: map[string][]string{
			"register": []string{"email", "username", "password"},
			"login":    []string{"email_or_username", "password"},
		},
	}
```

Thanks!

**Comment by IvRRimum** [comment]
And in the Read:
```
func (h HTTPBodyReader) Read(page string, r *http.Request) (authboss.Validator, error) {
	var values map[string]string
        ...
	case "login":
		var pid string
		if h.UseUsername {
			pid = values[FormValueUsername]
		} else {
			pid = values[FormValueEmail]
		}
```

It looks like this functionality is not supported.

**Comment by aarondl** [comment]
That's what I was saying.

> You can replace this interface to do anything you want. Here its configurable to take username or email.

You need to implement your own BodyReader to accept whatever string you want. Or improve the current one to be more flexible.

**Comment by IvRRimum** [comment]
Hmm... Okey, big thanks for clarification.
