### ISSUE TITLE
V2 Confirm in API mode: Does not work.

### ISSUE THREAD

**Issue by IvRRimum** [volatiletech/authboss#176]
I get a log:
`
22:34:07.375 func1 ▶ INFO 004 POST /v1/auth/confirm?cnf=SKi5iX1vWFscN/FOU3e1RUAIhg5yyMJorFAVni+cDGsqcfBCVle0T9fbwDSF6TetR+SB8bRQJpNx95BAcjzSSA==
`
If i use **GET** It complains about the JSON body that it's unable to decode.
Nothing happens.

**Comment by IvRRimum** [comment]
* the POST requests returns `404 not found`

**Comment by IvRRimum** [comment]
Looks like it's the similar to the responders and all that. Closing

**Comment by aarondl** [comment]
@IvRRimum Sorry to hear that. Anything I could change to make it work better? Love to hear some solid feedback from someone who tried it out and decided to throw it out.
