### ISSUE TITLE
Docs run off the edge of godoc.org

### ISSUE THREAD

**Issue by natefinch** [volatiletech/authboss#183]
A lot of the docs for Authboss run off the edge of godoc.org, which makes them difficult to read:

![image](https://user-images.githubusercontent.com/3185864/44408367-3d47e280-a52e-11e8-903a-c2a25e4f0098.png) 

It looks like the width is 87 characters (80 characters plus a 4-space tab, double slash, and a space).

**Comment by aarondl** [comment]
I guess that's a caveat of reading the docs with godoc.org, never thought about this. I'll try to fix it before release. Thanks!

**Comment by aarondl** [comment]
Well Nate. I finally bit the bullet and fixed this in the dev branch. Almost wrote a program to do it, then just bruteforced it :( I've got a bunch of new functionality that is pending release in that branch so it'll be fixed when that comes out. I hope Authboss is working out for you. Not sure if you saw but I released v2 and added 2fa support :)

**Comment by natefinch** [comment]
I missed the 2fa. That's awesome.

We're using aurhboss as the backend for https://GitHub.com/Mattel/archimedes
which is going to power Mattle's oauth service :)
