### ISSUE TITLE
v2 requiring user authentication to change password

### ISSUE THREAD

**Issue by scottjbarr** [volatiletech/authboss#184]
Hi

I was looking at implementing change password using the v2 branch.

For this feature, the logged in user would provide their current password, the new password and a new confirmation password.

The process would have 2 high level steps

1. authenticate the user (PID from the cookie, `password` from the POST data)
2. change the password to the new password (`new_password` and `confirm_password` from POST data).

While building this I noticed that authentication is tied to HTTP concerns, which I found prevents this from working.

To work with the current architecture with (validators etc) the HTTP body ends up being read twice, which doesn't work at the 2nd read will fail (body is empty as it has been read).

I propose refactoring the `Auth.LoginPost` method to separate the HTTP concerns from the authentication concerns. I've had a brief look at this, but it might be a non-trivial exercise given the way that the HTTP request and response are passed around. For example validators read data from the body, events require the HTTP request and response.

Changing password works easily if I do not attempt to use `Auth.LoginPost` as it currently stands as the HTTP body is only read once.

It may be that I'm missing something obvious here, and that there is a very easy way to do this without any refactoring.

Thoughts?

**Comment by aarondl** [comment]
Hey there @scottjbarr. `auth.LoginPost` is an HTTP handler so separating the HTTP concerns out of it would be a bit odd.

Authboss does a lot to abstract away the HTTP stack behind all these interfaces. But if I were you and I was dealing with my own web application I would ignore all of this and implement my own handler that doesn't have to jump through hoops to read a couple of values from the POST data and compare some passwords.

```go
// Your handler in your application
func changePasswordHandler(w http.ResponseWriter, r *http.Request) {
  user, err := myAuthboss.CurrentUser(r)
  if err != nil {
    // Error
  }

  u := user.(MyUserType)

  old := r.FormValue("old_password")
  password := r.FormValue("new_password")
  confirm := r.FormValue("new_password_confirm")

  if len(password) != 0 {
    // Error
  }

  if password != confirm {
   // Error
  }

  if err := bcrypt.CompareHashAndPassword([]byte(u.Password), []byte(old); err != nil {
    // Error
  }

  if err := myAuthboss.UpdatePassword(r.Context(), u, password); err != nil {
    // Error
  }

  // Render some kind of response
}
```

This is how you could do it. A follow-up question that I have would be is there some reason the above is undesirable? LoginPost does something very different than changing passwords, it authenticates a user and sets session variables on him to say that he's logged in. Maybe you'd like to extract the part that checks the password against the one in the database? A simple helper could be made to wrap the bcrypt call that's required but it doesn't save you too much code (one line for one line).

**Comment by scottjbarr** [comment]
With regards to handlers, I build them to entirely separate HTTP from the services a package provides. For example, I would aim to be able to authenticate a user with a set of given credentials that function, without knowing about a HTTP request/response.

I could wrap the existing code up by copy/pasting (and that is what I've done), but it seems rough to me. In refactoring I aimed to avoid that, allowing me to leverage the core features of the package.

If it isn't intended to be used that like, that's ok.

**Comment by scottjbarr** [comment]
Thanks @aarondl.
