### ISSUE TITLE
Inviting new users

### ISSUE THREAD

**Issue by stephenafamo** [volatiletech/authboss#186]
Is there a way to model an "invite user" flow. I'm thinking this may be possible with the confirm module.

What I have in mind is this.

A method is called using the user's email. The user is then "registered" but not confirmed.
So the confirm flow is triggered, along with a password reset.

**Comment by stephenafamo** [comment]
Thank you, this helps.

Is there a method to automatically trigger Recovery?

**Comment by aarondl** [comment]
I'm not sure what you mean by automatically. There is no such function regardless though, you'll have to piece it together yourself. Just remember that you can send the e-mail and generate the recover credentials with methods in that package so the only thing you have to do is set the right things in the user, the rest can be handled by other methods. Going to close this for now.

**Comment by stephenafamo** [comment]
Okay, understood. 

What I meant was a method say `authboss.Recover(pid)` which will then make the flow happen.
But I guess I'll have to piece this together.
