### ISSUE TITLE
 application/json;charset=utf-8  not  work

### ISSUE THREAD

**Issue by smirkcat** [volatiletech/authboss#189]
https://github.com/volatiletech/authboss/blob/master/defaults/responder.go#43

i use $.ajax(
        {
            url: uri,
            type: method,
            datatype: "JSON",
            contentType: 'application/json;charset=utf-8',
            data: JSON.stringify(data),
....

it's not work  

i use contentType: 'application/json',  ok  ##

i think r.Header.Get("Content-Type") == "application/json"

should be replaced by

strings.HasPrefix(r.Header.Get("Content-Type"),"application/json") 

or 

strings.Contains(r.Header.Get("Content-Type"),"application/json")

**Comment by aarondl** [comment]
Fixed in dev branch. Thanks!
