### ISSUE TITLE
use json  How to prohibit jumping

### ISSUE THREAD

**Issue by smirkcat** [volatiletech/authboss#190]
I  change the code 307 to 200 or  302   use  ajax
 Why url still jumps
when  use code 200
use /auth/logout  not jumps
but use /auth/login   jumps

**Comment by aarondl** [comment]
It always does a redirect. The code doesnt matter much. To avoid redirecting on an api style request see the dev branch and the new option on the defaults Responder. The CHANGELOG has some details.

**Comment by smirkcat** [comment]
I have already seen ，and I  But I still don't understand
E.g  I login with email=xxxxxx@gmail.com  password=1234  in url http://localhost:8080 
with api http://localhost:8080/auth/login
No matter what code 302 200 307 then the Browser  will jump to
http://localhost:8080/?email=xxxxxx%40gmail.com&password=1234
but  http://localhost:8080//auth/logout not jump 
Can tell me why ？
Even  the firfox can not get the set-cookie  ，Only once or twice can get the set-cookie also jump
I use jquery  3.3.1

**Comment by aarondl** [comment]
I'm actually having a lot of trouble understanding what you're trying to say.
You're using the dev branch, you've set this bool to true: https://github.com/volatiletech/authboss/blob/dev/defaults/responder.go#L57
And it's still redirecting?

**Comment by frederikhors** [comment]
Related in some way to https://github.com/volatiletech/authboss/issues/251?

**Comment by aarondl** [comment]
Stale.
