### ISSUE TITLE
REST mode: Confirm user is not working

### ISSUE THREAD

**Issue by ridhamtarpara** [volatiletech/authboss#194]
Confirm user endpoint: GET /auth/confirm?cnf=selector

So when I hit the get request with JSON API default HTTPBodyReader ends up with "failed to parse json http body" as it is trying to parse body which will be not available in get request.

This is the same issue as : https://github.com/volatiletech/authboss/issues/176

**Comment by aarondl** [comment]
When you're using the API version, you are supposed to send the `cnf` in a JSON body, not in a query string. It's for consistency since no query strings are used to pass data in a JSON api typically.

**Comment by ridhamtarpara** [comment]
Thank you! @aarondl I might be using old version so I will update this
