### ISSUE TITLE
Error while confirming Registrasion

### ISSUE THREAD

**Issue by sadiq1971** [volatiletech/authboss#195]
After registration, when i paste the confirm link in my browser and hit enter, i get this error:
`
2018-10-31T08:14:15Z [EROR]: request error from (127.0.0.1:54604) /confirm?cnf=B5h-5Zi1CDd0uFGvTDWQu0Y-j2xu9GXeyEqZWx7dfypGRYotwSrewHCghG2j7O_I6Rju38k7Xz5_OXgi2LcTww%3D%3D: unexpected end of JSON input
failed to parse json http body
github.com/volatiletech/authboss/defaults.HTTPBodyReader.Read
        /home/sadiq/go/src/github.com/volatiletech/authboss/defaults/values.go:216
github.com/volatiletech/authboss/defaults.(*HTTPBodyReader).Read
        <autogenerated>:1
github.com/volatiletech/authboss/confirm.(*Confirm).Get
        /home/sadiq/go/src/github.com/volatiletech/authboss/confirm/confirm.go:172
github.com/volatiletech/authboss/confirm.(*Confirm).Get-fm
        /home/sadiq/go/src/github.com/volatiletech/authboss/confirm/confirm.go:58
github.com/volatiletech/authboss/defaults.errorHandler.ServeHTTP
        /home/sadiq/go/src/github.com/volatiletech/authboss/defaults/error_handler.go:39
github.com/volatiletech/authboss/defaults.(*errorHandler).ServeHTTP
        <autogenerated>:1
net/http.(*ServeMux).ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:2337
github.com/volatiletech/authboss/defaults.(*Router).ServeHTTP
        /home/sadiq/go/src/github.com/volatiletech/authboss/defaults/router.go:64
net/http.StripPrefix.func1
        /usr/lib/go-1.10/src/net/http/server.go:1986
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/go-chi/chi.(*Mux).Mount.func1
        /home/sadiq/go/src/github.com/go-chi/chi/mux.go:291
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/volatiletech/authboss.ModuleListMiddleware.func1.1
        /home/sadiq/go/src/github.com/volatiletech/authboss/module.go:123
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/go-chi/chi.(*ChainHandler).ServeHTTP
        /home/sadiq/go/src/github.com/go-chi/chi/chain.go:31
github.com/go-chi/chi.(*Mux).routeHTTP
        /home/sadiq/go/src/github.com/go-chi/chi/mux.go:424
github.com/go-chi/chi.(*Mux).(github.com/go-chi/chi.routeHTTP)-fm
        /home/sadiq/go/src/github.com/go-chi/chi/mux.go:368
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/go-chi/cors.(*Cors).Handler.func1
        /home/sadiq/go/src/github.com/go-chi/cors/cors.go:201
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
main.dataInjector.func1
        /home/sadiq/go/src/github.com/imploy/auth-api/main.go:370
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/volatiletech/authboss/remember.Middleware.func1.1
        /home/sadiq/go/src/github.com/volatiletech/authboss/remember/remember.go:79
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/volatiletech/authboss.(*Authboss).LoadClientStateMiddleware.func1
        /home/sadiq/go/src/github.com/volatiletech/authboss/client_state.go:111
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/justinas/nosurf.(*CSRFHandler).handleSuccess
        /home/sadiq/go/src/github.com/justinas/nosurf/handler.go:179
github.com/justinas/nosurf.(*CSRFHandler).ServeHTTP
        /home/sadiq/go/src/github.com/justinas/nosurf/handler.go:136
main.logger.func1
        /home/sadiq/go/src/github.com/imploy/auth-api/middleware.go:59
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:1947
github.com/go-chi/chi.(*Mux).ServeHTTP
        /home/sadiq/go/src/github.com/go-chi/chi/mux.go:81
net/http.serverHandler.ServeHTTP
        /usr/lib/go-1.10/src/net/http/server.go:2694
`

**Comment by akhilmhdh** [comment]
Hey @sadiq1971 

Can you recall how did you solve this. I am also facing the same issue
