### ISSUE TITLE
Authboss and GoBuffalo integration almost done. Just some troubles. Any hint?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#202]
GoBuffalo author markbates told me (https://github.com/volatiletech/authboss/issues/163) that he does not use `authboss` and so for now he can not spend time integrating it with `buffalo`.

I'm opening this in case @aarondl or someone else can **understand in a moment** what is wrong with this: https://github.com/frederikhors/buffalo-authboss-sample

**Stackoverflow question**: https://stackoverflow.com/questions/53742344/gobuffalo-and-authboss-authentication-system-integration

I think I'm almost there, just something wrong, I don't understand what.

**Comment by frederikhors** [comment]
Dear @aarondl first of all thanks for your answer.

- I'm not using `auth` module, at least I think; in my `go.mod` I just have:

```
github.com/volatiletech/authboss v2.1.1+incompatible
github.com/volatiletech/authboss-renderer v0.0.0-20181105062701-4b64de40529a
```

- `ab.Init` is called in `actions/app.go` in this code:

```go
func setupAuthboss() {
	ab.Config.Paths.RootURL = "http://localhost:3000"

	ab.Config.Storage.Server = database

	ab.Config.Core.ViewRenderer = abrenderer.NewHTML("/auth", "ab_views")

	defaults.SetCore(&ab.Config, false, false)

	if err := ab.Init(); err != nil {
		panic(err)
	}
}
```

which is called by `setupAuthboss()`.

I copied from `authboss-sample` `blog.go` file.

(_It's driving me crazy!_)

**Comment by aarondl** [comment]
The auth module is inside authboss. That's the thing that registers and responds to the route `/login`. If you do not use it you will never be able to log in.

In order to use it, you must side effect import it to load it:
https://github.com/volatiletech/authboss-sample/blob/master/blog.go#L20

Documented here:
https://github.com/volatiletech/authboss#available-modules

**Comment by frederikhors** [comment]
Ok. Now I tried. Same problem but I think now it's really `init`ing...

![image](https://user-images.githubusercontent.com/41120635/49895786-ad69d380-fe51-11e8-95db-447084c69fcd.png)

But now anyway same problem: `404 page not found`.

**Comment by frederikhors** [comment]
@aarondl I committed side-effect imports (just `auth` and `logout`) and a middleware, at least I think it is ok: `LoadClientStateMiddleware`. If enabled Buffalo doesn't show anymore any route "/auth/*" in dashboard "/".

Commit: https://github.com/frederikhors/buffalo-authboss-sample/commit/d0e7c99c2fc01a8c16424108ead65d972695a6a0

Same problem anyway: `404 page not found`.

**Comment by frederikhors** [comment]
@aarondl are you ok? Did you miss my answers?

> Older authboss modules (like auth, the one you're trying to use)

Why did you write "older"?

**Comment by frederikhors** [comment]
I can close this because of https://github.com/gobuffalo/buffalo/issues/1506.
