### ISSUE TITLE
Is there a way or a config to add every endpoint a final slash?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#203]
I'm trying `GoBuffalo` integration but Buffalo doesn't like endpoints without final slash.

**Is there a way or a config to add every endpoint a final slash?**

Example: now it is: `/login`, Buffalo needs `/login/`.

**Comment by aarondl** [comment]
You can create a Middleware to modify the request by stripping the slash and then pass that modified request on to the authboss router.
