### ISSUE TITLE
Readme, modules name Remember used also for otp ones. Misprint?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#211]
In Readme (https://github.com/volatiletech/authboss/blob/master/README.md) I see this:

![image](https://user-images.githubusercontent.com/41120635/50728356-a40a1900-1128-11e9-8d7f-a95d83e6c10f.png)

**Remember** is the correct name for that modules? Misprint?

- Remember | github.com/volatiletech/authboss/otp/twofactor
- Remember | github.com/volatiletech/authboss/otp/twofactor/totp2fa
- Remember | github.com/volatiletech/authboss/otp/twofactor/sms2fa

**Comment by aarondl** [comment]
Misprint :) Fixed on dev. Not sure why I missed this issue btw. Sorry!
