### ISSUE TITLE
Remember me with or without checkbox in authboss-sample save "rm" cookie and session in DB anyway.

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#215]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

"Remember me" checkbox checked or not also in `authboss-sample` save "`rm`" cookie and session in DB anyway.

Screens:

- Checkbox checked
![image](https://user-images.githubusercontent.com/41120635/50790798-3690f080-12c0-11e9-9817-9e7066fa9273.png)

![image](https://user-images.githubusercontent.com/41120635/50790852-5d4f2700-12c0-11e9-90c5-0dc49e52e19a.png)

----

- Checkbox **UN**checked

![image](https://user-images.githubusercontent.com/41120635/50790885-76f06e80-12c0-11e9-9be0-9054c31c6cb7.png)

![image](https://user-images.githubusercontent.com/41120635/50790917-896aa800-12c0-11e9-8511-183d613412b8.png)

**Comment by aarondl** [comment]
Must be a bug. Will look into this.

**Comment by aarondl** [comment]
Fixed in dev branch of authboss. All these fixes are getting released to master pretty soon.

**Comment by frederikhors** [comment]
> Fixed in dev branch of authboss. All these fixes are getting released to master pretty soon.

I think you mean `master` branch of https://github.com/volatiletech/authboss-clientstate, right?

**Comment by aarondl** [comment]
I definitely forgot to push this btw. Sorry about that. It's in the dev branch now.
