### ISSUE TITLE
Remember me cookie in authboss-sample has MaxAge=Session. Explanation.

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#217]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

Using `authboss-sample` to understand `authboss` I noticed something that is strange maybe just for me because I still do not understand how it works authboss's `remember me` module. Maybe.

When a "`rm`" cookie is created I found in browser two cookies:

- `ab_blog` and
- `rm`.

Both have "`Expires / Max-Age`" = "`Session`" which I think is until browser get closed (or at least should be).

![image](https://user-images.githubusercontent.com/41120635/50790917-896aa800-12c0-11e9-8511-183d613412b8.png)

Now I think `authboss-sample` is rightly an example and so we need to set appropriately our settings like: 

```go
...
cookieStore = abclientstate.NewCookieStorer(cookieStoreKey, nil)
cookieStore.HTTPOnly = true
cookieStore.Secure = true
cookieStore.MaxAge = 7776000 // 90 days for example
```

Am I right? Or am I still omitting - blatantly - something already written somewhere?

In the case - very easily - I'm wrong, how can a "remember" cookie last only until the browser is closed? Does this make sense?

**Comment by aarondl** [comment]
This was a bug in the authboss-clientstate library (introduction of the max age configuration made this bug) which has been fixed.
