### ISSUE TITLE
Defaults HTTPBodyReader with ReadJSON option don't accept empty body.

### ISSUE THREAD

**Issue by SlevinWasAlreadyTaken** [volatiletech/authboss#226]
Hello,

I have opened a PR https://github.com/volatiletech/authboss/pull/225 here presenting an issue and suggesting a change to fix it.
The title of the issue summarise the issue but more information are available in the **PR description**.

I didn't know if it was better to create first an issue before a PR so I create both to ensure it is not missed.

Thanks for your understanding,
Have a good day.

**Comment by aarondl** [comment]
Hi Slevin. I don't work on this stuff frequently, I batch my work on it so it gets my attention maybe once every few weeks. I'll take a look at your PR.
