### ISSUE TITLE
Remember me, expired tokens in DB table

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#228]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

I'm trying to use the following model for the "remember me" module.

```go
type AuthToken struct {
	Pid       string `sql:"type:varchar(100)"`
	Token     string
	CreatedAt time.Time `sql:"default:now()"`
}
```

I'm wondering what to do with tokens in the table DB that are older than the maximum token expiration period.

A simple `DELETE ... WHERE created_at > 30 days`?

Do you think there is a mistake doing this, @aarondl?

**Comment by aarondl** [comment]
This is fine. Though you need to decide where to do that. Many websites have some sort of `cron` job system that's running in the background for these sorts of cleanup tasks. You could add it to that, or if you wanted to simplify things you could add the `delete` where you look up the token, this makes looking up tokens slower, but the cleanup then becomes simplified.
