### ISSUE TITLE
Integration in revel framework

### ISSUE THREAD

**Issue by freemanpolys** [volatiletech/authboss#231]
How to register **ab.Config.Core.Router**  with Revel framework ?

**Comment by aarondl** [comment]
This is an exercise left for the reader. Authboss is compatible with the most basic of Go primitives in the http package, and therefore it's assumed it can work with any level of fancy web framework like revel, but how much work that is to do for your chosen framework could vary and it may be impossible depending on how they've decided to do things. Good luck!
