### ISSUE TITLE
Use Authboss with GraphQL only

### ISSUE THREAD

**Issue by Pokerkoffer** [volatiletech/authboss#238]
Hi,
i am currently developing a Client/Server application with a web frontend. Communication between backend and frontend is handled via a GraphQL API.

This library looks very promising and i am wondering if it is possible to use authboss only with an GraphQL api (e.g. login/signup/logout mutations, currentUser query)

I've seen that there are json/html renderer, are they mandatory? Is the router required by authboss as well or can I extract the required data and respond via the api to the web frontend?

I don't want a mix of REST and GraphQL endpoints, therefore I try to keep it GraphQL only.

Thanks!

**Comment by aarondl** [comment]
Authboss is a collection of interfaces that work together to do things like persist session states, database states, render responses, read requests. You should in theory be able to replace these interfaces with ones that behave enough like graphql that your application doesn't need to be too weird when dealing with authboss.

But I will say as far as I know graphql is definitely not a good fit for this kind of an API as it's mostly about reading data in a variety of ways where as this is a stateful mess of get/posts etc.

**Comment by Pokerkoffer** [comment]
Ok, thank you for clarification.

**Comment by frederikhors** [comment]
@Pokerkoffer did you accomplish this task? Are you using authboss with graphql?

**Comment by Pokerkoffer** [comment]
> @Pokerkoffer did you accomplish this task? Are you using authboss with graphql?

No, authboss is tied too much to REST. I implemented my own authentication / authorization and session solution following these important best practices:

- https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html
- https://cheatsheetseries.owasp.org/cheatsheets/Transaction_Authorization_Cheat_Sheet.html
- https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html

It's easy to get something wrong and render your implementation useless / insecure so make sure to read it and understand it before implementing.

**Comment by frederikhors** [comment]
Amazing. I like what you said.

What do you think about making your solution open source?

**Comment by Pokerkoffer** [comment]
> What do you think about making your solution open source?

It is far from being finished, so no, not in the near future. You can use Ory Hydra however, if it fits your use case https://github.com/ory/hydra

**Comment by frederikhors** [comment]
If you push your code it would be soon being finished... :)
