### ISSUE TITLE
Use with precompiled templates, eg. with Quicktemplate

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#239]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

---

I'm trying to use `authboss` with [`quicktemplate`](https://github.com/valyala/quicktemplate) but I'm having some problems.

If I read the code for [`html.go`](https://github.com/volatiletech/authboss-renderer/blob/master/html.go) I can see `Load()` and `Render()` methods.

I started copying that code and if I understand correctly:

- the `Load()` method: I think I don't need it (for my basic work). Am I wrong? Some comments of mine in the original code:

```go
func (h *HTML) Load(names ...string) error {
    if h.layout == nil {
        b, err := loadWithOverride(h.overridePath, "html-templates/layout.tpl") // I use an interface for layout page with quicktemplate
        if err != nil {
            return err
        }
        h.layout, err = template.New("").Funcs(h.funcMap).Parse(string(b)) // I don't need parsing anymore
        if err != nil {
            return errors.Wrap(err, "failed to load layout template")
        }
    }
    for _, n := range names {
        filename := fmt.Sprintf("html-templates/%s.tpl", n) // this is already an object in my code, right?
        b, err := loadWithOverride(h.overridePath, filename)
        if err != nil {
            return err
        }
        clone, err := h.layout.Clone() // this is already an object in my code, right?
        if err != nil {
            return err
        }
        _, err = clone.New("authboss").Funcs(h.funcMap).Parse(string(b)) // this is already an object in my code, right?
        if err != nil {
            return errors.Wrapf(err, "failed to load template for page %s", n)
        }
        h.templates[n] = clone // maybe something like this with functions?
    }
    return nil
}
```

- for the `Render()` method I can use something like this:

```go
func (h *HTML) Render(ctx context.Context, page string, data authboss.HTMLData) (output []byte, contentType string, err error) {
	// -------> Original authboss one, commented now
	// buf := &bytes.Buffer{}
	// tpl, ok := h.templates[page]
	// if !ok {
	// return nil, "", errors.Errorf("template for page %s not found", page)
	// }
	// err = tpl.Execute(buf, data)
	// if err != nil {
	// return nil, "", errors.Wrapf(err, "failed to render template for page %s", page)
	// }

	// -------> Mine
	buf := &bytes.Buffer{}
	templates.WritePage(buf, &templates.LoginPage{
		Data: data,
	})
	return buf.Bytes(), "text/html", nil
}
```

**which has the problem** I cannot dynamically load pages in `templates.WritePage()` method based on `page` parameter.

`LoginPage` is coming from a template like this:

```quicktemplate
{% import "github.com/volatiletech/authboss" %}

{% code
    type LoginPage struct { Data authboss.HTMLData } 
%}

{% func (p *LoginPage) Title() %}
    Login
{% endfunc %}

{% func (p *LoginPage) Body() %}
    <b>Data: {%v p.Data.Something %}</b>
    <form action="/login" method="POST">
        <input type="email">
        <input type="password">
        <button>Login</button>
        {% if p.Data["modules"] != nil %} 
            Something else with modules...
        {% endif %}
    </form>
{% endfunc %}
```

Maybe with reflection? Really? I read everywhere reflection is really slow and I need to use something else if possible.

I tried also with something like this:

```quicktemplate
{% import "github.com/volatiletech/authboss" %}

{% code var ALL_TEMPLATES map[string]*LoginPage %}

{% code
    func init() {
        ALL_TEMPLATES = make(map[string]*LoginPage)
        ALL_TEMPLATES["login"] = &LoginPage{}
    }
%}

{% code
    type LoginPage struct { Data authboss.HTMLData } 
%}

{% func (p *LoginPage) Title() %}
    Login
{% endfunc %}

{% func (p *LoginPage) Body() %}
    <b>Data: {%v p.Data.Something %}</b>
    <form action="/login" method="POST">
        <input type="email">
        <input type="password">
        <button>Login</button>
        {% if p.Data["modules"] != nil %} 
            Something else with modules...
        {% endif %}
    </form>
{% endfunc %}
```

but I think something is wrong here. I don't like `ALL_TEMPLATES` slice way of doing this.

What do you suggest?

---

I already opened an issue on `quicktemplate` repo: https://github.com/valyala/quicktemplate/issues/58.

**Comment by aarondl** [comment]
I'd say that your problem is that you're not using the Load() stuff correctly. Load should compile the template and store them in a map[string]template or what have you. That way when Render is called, the right template can be referenced.

**Comment by frederikhors** [comment]
As I have already written here: https://github.com/valyala/quicktemplate/issues/58#issuecomment-517039441

### What have I done

Now I'm using `authboss.Renderer` interface's `Load()` method:

```go
type HTML struct {
  ...
  templates    map[string]func(authboss.HTMLData) templates.PageImpl
  ...
}

func InitializeLoginPageType(data authboss.HTMLData) templates.PageImpl {
	return &templates.LoginPage{Data: data}
}

func (h *HTML) Load(names ...string) error {
	for _, n := range names {
		switch n {
		case "login":
			h.templates[n] = InitializeLoginPageType
		}
	}
	return nil
}

func (h *HTML) Render(ctx context.Context, page string, data authboss.HTMLData) (output []byte, contentType string, err error) {
	buf := &bytes.Buffer{}
	tpl, ok := h.templates[page]
	if !ok {
		return nil, "", errors.Errorf("...")
	}
	templates.WritePage(buf, tpl(data))
	return buf.Bytes(), "text/html", nil
}
```

### The million dollar question

**Do you see problems with this code?**

> Load should compile the template

Is my final code correct using it with `quicktemplate` precompiled templates?

**Comment by aarondl** [comment]
This seems fine to me. Though I would not use the lambda. I'd probably try to use an interface and create all the structs inline in the switch case. :)

**Comment by frederikhors** [comment]
_Your advice is invaluable, thank you very much._

_I am still learning Go and every problem is an opportunity to learn, but only if I am "guided" by skilled and generous people like you._

I have created two different versions of the problem and would like to know which one is best.

1. https://github.com/frederikhors/authbossQuicktemplate_1, factory pattern and initializators

1. https://github.com/frederikhors/authbossQuicktemplate_2, with interface and a `SetData(data authboss.HTMLData) (page PageImpl)` method

I think you prefer the latter, but I don't know what to improve for the performances.

Do you think I can improve using pointers somewhere?

**Comment by aarondl** [comment]
Second one seems fine. Remember I'm not a code review service ;) I just make the library which is enough work on it's own. I think you're doing fine.
