### ISSUE TITLE
OAuth2User.IsOAuth2User() bool

### ISSUE THREAD

**Issue by jack-chung** [volatiletech/authboss#241]
This function does not seem to be used anywhere, but is required as part of the interface. Can you elaborate on the purpose of this function?

My system allows one standard login to be linked with zero to multiple OAuth2 social accounts. I'm a bit unsure how to implement this function correctly without knowing more detail on how it will be used.

**Comment by aarondl** [comment]
Hm. I can't right recall, I think the idea was to be able to report to the database whether or not it should be an insert or an update in the database. (Is this a new user?). OAuth2 doesn't really tell you if it's a new user or not in your own site, so I think this was made with that provision in mind.
