### ISSUE TITLE
How to prevent account recovery before confirmation

### ISSUE THREAD

**Issue by nan0tube** [volatiletech/authboss#243]
Faced the issue when I am trying to use both modules in an API setting.

Tried returning an error in `Authboss.Storage.Server.Save` under the condition; while it blocks the recovery, the HTTP response is also empty. Wonder if there is a way to signal the caller of the error.

**Comment by aarondl** [comment]
I thought I ran into something similar to this in recent times and I fixed it. Maybe not this particular case though.

I'm guessing the issue is you also have this turned on?: https://github.com/volatiletech/authboss/blob/master/config.go#L126

**Comment by nan0tube** [comment]
I did not set `RecoverLoginAfterRecovery` explicitly, so it is probably `false` for me.

**Comment by aarondl** [comment]
Stale.
