### ISSUE TITLE
Message {"status":"success"} on GET call on /login endpoint?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#248]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

---

I'm using authboss in API mode.

I wonder why I get the message `{"status":"success"}` on `GET` calls on `/login` endpoint?

**Comment by aarondl** [comment]
It's a layover from using authboss in API mode. Because it simply translates all the handlers to JSON, the handler for `GET` from the http side is still there. It has no effects, it renders empty JSON so it shouldn't matter. I realize it's annoying though.
