### ISSUE TITLE
Why is context data not passed to emails like in html pages?

### ISSUE THREAD

**Issue by Gys** [volatiletech/authboss#249]
In Responder.Respond() all context data in merged into the HTMLData before continuing to the rendering:

    ctxData := req.Context().Value(authboss.CTXKeyData)
    if ctxData != nil {
        if data == nil {
            data = authboss.HTMLData{}
        }
        data.Merge(ctxData.(authboss.HTMLData))
    }

This makes it possible to inject data early in the request handling for personalizing the html views. Very useful!

Unfortunately this is not done for rendering the emails. Is there a reason for that?

I think it would be useful to have the same code added to response.go func Mail()?

I now use a slightly modified version of the authboss-renderer package where I added this code into Email.Render(), to implement a.Core.MailRenderer.Render. This works just as well, but by moving it one level higher up, the core package would (and it should ;-) have this ability build-in.

**Comment by aarondl** [comment]
I'm not really opposed to this. Would accept a PR for it.

**Comment by Gys** [comment]
https://github.com/volatiletech/authboss/pull/254

**Comment by aarondl** [comment]
Closed by 928ca45
