### ISSUE TITLE
Is it possibile to use `CorceRedirectTo200` in master?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#251]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (https://github.com/volatiletech/authboss/issues/210)._

---

Is it possibile to use `CorceRedirectTo200` in master?

I'm using it like this:

```go
ab.Config.Paths.RootURL = os.Getenv("SITE_URL")
ab.Config.Storage.Server = database
ab.Config.Storage.SessionState = sessionStore
ab.Config.Storage.CookieState = cookieStore
ab.Config.Modules.LogoutMethod = "GET"
ab.Config.Core.ViewRenderer = defaults.JSONRenderer{}
ab.Config.Core.Redirector = &defaults.Redirector{CorceRedirectTo200: true}
defaults.SetCore(&ab.Config, true, false)
```

but still I have a `GET` -> `localhost/auth/logout` -> redirected to -> `/`.

**Why?**

**How to disable redirect and just use 200?**

**Comment by aarondl** [comment]
Your problem is that the call to `defaults.SetCore` overrides your redirector you just set up :p

**Comment by frederikhors** [comment]
@aarondl long time to respond I know.

I inverted lines from this:

```go
ab.Config.Paths.RootURL = os.Getenv("SITE_URL")
ab.Config.Storage.Server = database
ab.Config.Storage.SessionState = sessionStore
ab.Config.Storage.CookieState = cookieStore
ab.Config.Modules.LogoutMethod = "GET"
ab.Config.Core.ViewRenderer = defaults.JSONRenderer{}
ab.Config.Core.Redirector = &defaults.Redirector{CorceRedirectTo200: true}
defaults.SetCore(&ab.Config, true, false)
```

to this:

```go
ab.Config.Paths.RootURL = os.Getenv("SITE_URL")
ab.Config.Storage.Server = database
ab.Config.Storage.SessionState = sessionStore
ab.Config.Storage.CookieState = cookieStore
ab.Config.Modules.LogoutMethod = "GET"
ab.Config.Core.ViewRenderer = defaults.JSONRenderer{}
defaults.SetCore(&ab.Config, true, false)
ab.Config.Core.Redirector = &defaults.Redirector{CorceRedirectTo200: true}
```

and the problem is still there:

I still have a `GET` -> `localhost/auth/logout` -> redirected to -> `/`.

**Why?**

**Comment by frederikhors** [comment]
Isn't `ab.Config.Core.Redirector = &defaults.Redirector{CorceRedirectTo200: true}` setting a config in the `&ab.Config` I will use after in `defaults.SetCore(&ab.Config, true, false)`?

_Authboss is great but this config is sometimes too complicated for newbies and simple people like me. :(_

**Comment by frederikhors** [comment]
Ok. After small investigation I understood the problem is this line: https://github.com/volatiletech/authboss/blob/master/defaults/responder.go#L44.

The `func isAPIRequest()` because I was trying with Postman without Content-Type.

The problem now is I have errore on login, on logout (line 103 of `responder.go`: `body, mime, err := r.Renderer.Render(req.Context(), "redirect", data)`) because I think my `Renderer` struct is missing.

**Comment by frederikhors** [comment]
Little news:

I was able to make it work like this:

```go
defaults.SetCore(&ab.Config, true, false)
ab.Config.Core.Redirector = &defaults.Redirector{Renderer: &defaults.JSONRenderer{}, CorceRedirectTo200: true}
```

but still don't know why with `defaults.SetCore()` I have `FormValueName: "redir"`.

Is there a doc somewhere?

I can write it if I can understand.

**Comment by aarondl** [comment]
https://github.com/volatiletech/authboss/blob/master/defaults/defaults.go#L25
https://github.com/volatiletech/authboss/blob/master/response.go#L11-L14

Do these links help?
