### ISSUE TITLE
Great Work on Authboss and Abrenderer

### ISSUE THREAD

**Issue by siredwin** [volatiletech/authboss#261]
I have fully implemented your package and it is great. My life will be 10 times easier from now onwards.
You put a lot of thought into it.
It also has a bit of a learning curve.
This package almost needs a manual!
That said I will probably look into implementing more providers and contributing.
I would have donated coffee here if you accepted it!

**Comment by aarondl** [comment]
Thanks for the kind comments.

It is a difficult package to implement as I've noted elsewhere. I have no idea how I would be able to make it simpler without making it less flexible unfortunately. Glad you persevered and found some value in it though :)

I welcome your contributions when the time comes too.
