### ISSUE TITLE
Nilness analysis

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss#278]
- `confirm.go`:
Function call 'callbackMethod("/confirm", c.Authboss.Config.Core.ErrorHandler.Wrap(c.Get))' may lead to nil pointer dereference

- `oauth2_test.go`:
Method call 'err.Error()' may lead to nil pointer dereference 
Method call 'err.Error()' may lead to nil pointer dereference 
Method call 'err.Error()' may lead to nil pointer dereference 

- `totp.go`:
'user' may have 'nil' or other unexpected value as its corresponding error variable may be not 'nil' 

- `validation.go`:
Method call 'err.Error()' may lead to nil pointer dereference

**Comment by aarondl** [comment]
I fixed the one in confirm.go, the others are benign and reasonably guaranteed not to be nil in some other way.
