### ISSUE TITLE
307 redirect on login after setting JSON API flag

### ISSUE THREAD

**Issue by anselm94** [volatiletech/authboss#285]
Authboss doesn't map [`readJSON` parameter in `defaults.SetCore`](https://github.com/volatiletech/authboss/blob/master/defaults/defaults.go#L25) to [`CorceRedirectTo200` parameter in `defaults.Redirector`](https://github.com/volatiletech/authboss/blob/020487826a5df9ed53b5ff2a749432bb8fec7c30/defaults/responder.go#L57)

The signature of [`defaults.NewRedirector`](https://github.com/volatiletech/authboss/blob/020487826a5df9ed53b5ff2a749432bb8fec7c30/defaults/responder.go#L61) has to be updated to include the API flag param

https://github.com/volatiletech/authboss/blob/020487826a5df9ed53b5ff2a749432bb8fec7c30/defaults/responder.go#L61

**Comment by aarondl** [comment]
Yeah. It's a sad reality but it would have been a breaking change so we opted not to make it, there are many such issues we'd like to change in v3. You can still use `SetDefaults` and then convert & set the value yourself in the Redirector, or you can create your own version of SetDefaults and ensure that its set appropriately. Thanks for raising the issue.
