### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by sebastianmacias** [volatiletech/authboss#287]
Is there an example project that has all of the configuration and allow new users to quickly get started?

**Comment by lu4p** [comment]
Yes https://github.com/volatiletech/authboss-sample

Easy to get started is an overstatement didn't get authboss to work with echo, now implementing my own solution.

**Comment by aarondl** [comment]
Thanks for responding to him @lu4p.

And yes, his remark makes a lot of sense. Authboss is not easy under the best of circumstances. Steel yourself if you attempt it, and good luck!
