### ISSUE TITLE
Is it possible to share example of using authboss with Gin Gonic?

### ISSUE THREAD

**Issue by itsursujit** [volatiletech/authboss#291]
https://github.com/volatiletech/authboss/wiki/Integration-with-gin-gonic

Seems to be the old version and a lot of things are changed.

Is it possible to share example of using authboss with Gin Gonic?

**Comment by aarondl** [comment]
We don't support gin-gonic at all. Happy to take any updates to that example though.

**Comment by aarondl** [comment]
I should be more clear: We don't want to spend time creating an integration example for every Go framework out there. This one was contributed by a keen authboss user and the expectation is that that continues.

If it's stale then maybe it should be deleted if there is no one to update it though.

**Comment by itsursujit** [comment]
Oh okay! no problem
