### ISSUE TITLE
Enable go module please

### ISSUE THREAD

**Issue by videni** [volatiletech/authboss#295]
dep is block in China, and there is no mirror for dep, please enable go module.

**Comment by aarondl** [comment]
We can do this soon, but I want to ensure there's no breaking changes I need to include first. It's not high on my priority list right now unfortunately.

For now you can use it via the Go modules system simply by allowing it to use the incompatible type module imports. Just `go get github.com/volatiletech/authboss@somegithash`

**Comment by aarondl** [comment]
v3 is Go module-aware.

**Comment by joe-getcouragenow** [comment]
@aarondl 
Huge thank you !!
