### ISSUE TITLE
I want to use more usefully authboss on any framework.

### ISSUE THREAD

**Issue by lkeix** [volatiletech/authboss#311]
Hi!
authboss is very interested in OSS Project. I think authboss is very powerful tool when I develop web system not using framework. But, authboss is a little hard-to use using any framework (e.g. gin).
Therefore, I'll develop module to use authboss more usefully on any framework.

Does authboss require module like connecting to framework?

**Comment by aarondl** [comment]
Hi @lkeix. It sounds like an okay idea.

Authboss generally needs code to connect any application to it. And that code needs to be aware of the pieces that they use.

**Comment by lkeix** [comment]
Ok!
when I created connection code between framework and authboss, I'll mention or send pullrequest again.

**Comment by aarondl** [comment]
Okay thanks.
