### ISSUE TITLE
GRPC support 

### ISSUE THREAD

**Issue by eldad87** [volatiletech/authboss#312]
Hi,
I'm interested in using AuthBoss. By reviewing the documentation and relevant points in the source-code itself, it seems like the library is relaying heavily on it's middleware(s). 

I wonder if there is a way to use AuthBoss in a none-HTTP based environment, such as gRPC?

Please advise,
Thanks!

**Comment by aarondl** [comment]
The middlewares are replaceable. As long as you can fulfill the core interfaces. It'd be a decent amount of work, but you could make it happen.

**Comment by aarondl** [comment]
Also - I closed the issue because there is no official GRPC support and I'm not intending to make any. Be very curious to see where you got to if you attempted it though.
