### ISSUE TITLE
How to resolve this error ? with echo v4

### ISSUE THREAD

**Issue by p000ic** [volatiletech/authboss#335]
echo: http: panic serving 127.0.0.1:55619: ResponseWriter must be a ClientStateResponseWriter or UnderlyingResponseWriter in (see: authboss.LoadClientStateMiddleware): *echo.Response

**Comment by akhilmhdh** [comment]
Have you added the middleware `LoadClientStateMiddleware`

**Comment by p000ic** [comment]
Found the solution thanks.
