### ISSUE TITLE
How to do a retry confirmation email ?

### ISSUE THREAD

**Issue by akhilmhdh** [volatiletech/authboss#339]
Hey there,

I was playing around with authboss as a whole. Confirmation module works as expected. But out of curiosity wanted to try how to do a retry for confirmation mail to be sent again. Like scenarios in which user may have missed it etc.

I found out that [code](https://github.com/volatiletech/authboss/blob/e74112f6170d67dafda5c9a9033bda38cd9df4e5/confirm/confirm.go#L74) its added as register event effect. But read in documentation that i can be triggered with register hook.

Can someone please help me on, whether this is something achievable. I saw the function for it to start the flow but can't seem to get an idea on how to execute it.

**Comment by aarondl** [comment]
All the code is there and broken apart in such a way to make it easy to call the part you're interested in. I don't have enough context about your use case, but basically just call one of the methods:
`StartConfirmation`, `StartConfirmationWeb` or `SendConfirmEmail`
