### ISSUE TITLE
InitContext panic when not set CookieStoreMaker

### ISSUE THREAD

**Issue by azumads** [volatiletech/authboss#94]
I only use SessionStoreMaker, and want to get CurrentUser, it panic , is it on purpose？

CurrentUser call InitContext, InitContext call CookieStoreMaker.

// CurrentUser retrieves the current user from the session and the database.
func (a *Authboss) CurrentUser(w http.ResponseWriter, r *http.Request) (interface{}, error) {
    return a.currentUser(a.InitContext(w, r), w, r)
}

func (a *Authboss) InitContext(w http.ResponseWriter, r *http.Request) *Context {
    ctx := a.NewContext()
....
    ctx.SessionStorer = clientStoreWrapper{a.SessionStoreMaker(w, r)}
    ctx.CookieStorer = clientStoreWrapper{a.CookieStoreMaker(w, r)}

```
return ctx
```

}

**Comment by aarondl** [comment]
Will look into this. Is your use case that you don't want people to be able to click a "Remember Me" button? 

Trying to understand why you would have a session storer only.

**Comment by aarondl** [comment]
These interfaces should no longer be required if you're not using them in v2 (see releases page for more details).
